# Generated by Django 4.0.6 on 2024-10-11 10:41

import Location.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GarageSale', '0003_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', Location.models.MultipleChoiceField(default=['AdBoard,Sale'], max_length=500, null=True)),
                ('house_number', models.CharField(max_length=80)),
                ('street_name', models.CharField(max_length=200)),
                ('town', models.CharField(default='Brantham', max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventLocations', to='GarageSale.eventdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
