# Generated by Django 4.1 on 2025-03-15 16:49

import DjangoGoogleMap.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GarageSale', '0002_motd_supporting_eventdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_board', models.BooleanField(help_text='Do you want an advertising board at this location ?')),
                ('sale_event', models.BooleanField(help_text='Do you plan to have a sale or another event at this location ?')),
                ('house_number', models.CharField(max_length=80)),
                ('street_name', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('town', models.CharField(default='Brantham', max_length=100)),
                ('lng_lat', DjangoGoogleMap.models.fields.GoogleLocation(max_length=60)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventLocations', to='GarageSale.eventdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
