# Generated by Django 4.0.6 on 2024-10-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.AddField(
            model_name='location',
            name='ad_board',
            field=models.BooleanField(default=False, help_text='Do you want an advertising board at this location ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='sale_event',
            field=models.BooleanField(default=False, help_text='Do you plan to have a sale or another event at this location ?'),
            preserve_default=False,
        ),
    ]
