# Generated by Django 4.0.6 on 2025-09-22 11:45

import DjangoGoogleMap.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng_lat',
            field=DjangoGoogleMap.models.fields.GoogleLocation(max_length=60, verbose_name='Sale/AdBoard location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(blank=True, default='Brantham', max_length=100),
        ),
    ]
