# Generated by Django 6.0.1 on 2026-01-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_alter_location_house_number_alter_location_lng_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ad_board_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='sale_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
