# Generated by Django 4.0.6 on 2024-11-04 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_remove_location_category_location_ad_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='creation_timestamp',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
