# Generated by Django 4.1 on 2024-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_location_creation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
