# Generated by Django 4.1 on 2024-11-27 10:56

import DjangoGoogleMap.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0004_alter_location_creation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lng_lat',
            field=DjangoGoogleMap.models.fields.GoogleLocation(default=''),
            preserve_default=False,
        ),
    ]
