# Generated by Django 4.0.6 on 2024-02-01 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['email'], name='user_manage_email_faa22c_idx'),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['uuid'], name='user_manage_uuid_1ff849_idx'),
        ),
    ]
