# Generated by Django 4.1 on 2025-03-15 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=12)),
                ('is_guest', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GuestVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_timestamp', models.DateTimeField()),
                ('short_code', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('retry_count', models.IntegerField()),
                ('reason_code', models.CharField(choices=[('expired', 'Expired'), ('entry_error', 'Entry Error')], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_timestamp', models.DateTimeField()),
                ('uuid', models.UUIDField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_timestamp', models.DateTimeField()),
                ('uuid', models.UUIDField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='registrationverifier',
            index=models.Index(fields=['uuid'], name='byUUid'),
        ),
        migrations.AddIndex(
            model_name='passwordresetapplication',
            index=models.Index(fields=['uuid'], name='byUUID'),
        ),
        migrations.AddIndex(
            model_name='guestverifier',
            index=models.Index(fields=['short_code'], name='byShortCode'),
        ),
        migrations.AddField(
            model_name='additionaldata',
            name='verifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AdditionalData', to='user_management.registrationverifier'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
