# Generated by Django 5.0 on 2026-04-12 14:14

import django.db.models.deletion
import user_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Treasurer', 'Treasurer'), ('Volunteer', 'Volunteer'), ('Secretary', 'Secretary'), ('Committee Member', 'Committee Member')])),
                ('bio', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to=user_management.models.user_image_save_to)),
                ('team_member_id', models.SlugField(editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['team_member_id'], name='ByMemberId')],
            },
        ),
    ]
