# Generated by Django 4.0.6 on 2024-10-18 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userverification',
            name='user_manage_uuid_1ff849_idx',
        ),
        migrations.AddField(
            model_name='userverification',
            name='expiry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userverification',
            name='short_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='type',
            field=models.CharField(default='Null', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userverification',
            name='uuid',
            field=models.UUIDField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['uuid', 'type'], name='user_manage_uuid_1b5ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['short_code', 'type'], name='user_manage_short_c_a7ac39_idx'),
        ),
    ]
