# Generated by Django 4.0.6 on 2024-10-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_userverification_user_manage_uuid_1ff849_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='short_code',
            field=models.CharField(blank=True, default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='type',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='uuid',
            field=models.UUIDField(blank=True, default=None),
        ),
    ]
