# Generated by Django 5.0 on 2026-04-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'permissions': [('generate_id_card', 'Can generate ID cards')]},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Committee Member', 'Committee Member'), ('Treasurer', 'Treasurer'), ('Chairperson', 'Chairperson'), ('Secretary', 'Secretary'), ('Volunteer', 'Volunteer')]),
        ),
    ]
