# Generated by Django 4.0.6 on 2024-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_userverification_short_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userverification',
            name='user_manage_uuid_1b5ca9_idx',
        ),
        migrations.RemoveIndex(
            model_name='userverification',
            name='user_manage_short_c_a7ac39_idx',
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(condition=models.Q(('type', 'uuid')), fields=['type', 'uuid'], name='byUUid'),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(condition=models.Q(('type', 'short_code')), fields=['type', 'short_code'], name='byShortCode'),
        ),
    ]
