# Generated by Django 4.0.6 on 2024-10-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_userverification_user_manage_uuid_1b5ca9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='short_code',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
