# Generated by Django 4.0.6 on 2024-10-29 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_userverification_short_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_timestamp', models.DateTimeField()),
                ('short_code', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('retry_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_timestamp', models.DateTimeField()),
                ('uuid', models.UUIDField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
        migrations.AddIndex(
            model_name='registrationverifier',
            index=models.Index(fields=['uuid'], name='byUUid'),
        ),
        migrations.AddIndex(
            model_name='guestverifier',
            index=models.Index(fields=['short_code'], name='byShortCode'),
        ),
    ]
