# Generated by Django 4.0.6 on 2024-11-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_guestverifier_registrationverifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextended',
            old_name='is_restricted',
            new_name='is_guest',
        ),
        migrations.AddField(
            model_name='guestverifier',
            name='reason_code',
            field=models.CharField(choices=[('expired', 'Expired'), ('entry_error', 'Entry Error')], max_length=11, null=True),
        ),
    ]
