# Generated by Django 4.1 on 2024-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_rename_is_restricted_userextended_is_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationverifier',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
