# Generated by Django 4.1 on 2024-11-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_registrationverifier_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='mobile',
        ),
    ]
