# Generated by Django 4.1 on 2024-11-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_remove_userextended_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationverifier',
            name='password',
        ),
        migrations.AddField(
            model_name='userextended',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AdditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=128)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalData', to='user_management.registrationverifier')),
            ],
        ),
    ]
