# Generated by Django 4.1 on 2024-11-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_remove_registrationverifier_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaldata',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='additionaldata',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdditionalData', to='user_management.registrationverifier'),
        ),
    ]
