# Generated by Django 4.1 on 2024-11-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_rename_phone_number_additionaldata_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldata',
            name='verifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AdditionalData', to='user_management.registrationverifier'),
        ),
    ]
