# Generated by Django 4.1 on 2024-11-16 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_alter_additionaldata_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetapplication',
            name='creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='passwordresetapplication',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordresetapplication',
            name='expiry_timestamp',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='passwordresetapplication',
            index=models.Index(fields=['uuid'], name='byUUID'),
        ),
    ]
