# Generated by Django 4.1 on 2024-11-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_passwordresetapplication_creation_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetapplication',
            name='user',
        ),
    ]
