# Generated by Django 4.1 on 2024-11-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_remove_passwordresetapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
