# Generated by Django 4.1 on 2025-03-15 16:50

import datetime
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('publish_by', models.DateField(db_index=True, default=datetime.date.today)),
                ('expire_by', models.DateField(blank=True, db_index=True, null=True)),
                ('headline', models.CharField(max_length=256)),
                ('front_page', models.BooleanField(db_index=True, default=False)),
                ('content', django_quill.fields.QuillField(default='')),
                ('synopsis', models.CharField(blank=True, max_length=256, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_manage_news', 'Can manage the news Articles'), ('can_create_news', 'Can create a news Article'), ('can_publish_news', 'Can publish a news Article'), ('can_edit_news', 'Can edit a news Article'), ('can_view_news', 'Can view a news Article'), ('can_delete_news', 'Can delete a news Article')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NewsLetterMailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('last_sent', models.DateField(null=True)),
            ],
        ),
    ]
