# Generated by Django 4.0.6 on 2024-02-01 11:03

import datetime
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('publish_by', models.DateField(db_index=True, default=datetime.date.today)),
                ('expire_by', models.DateField(blank=True, db_index=True, null=True)),
                ('headline', models.CharField(max_length=256)),
                ('front_page', models.BooleanField(db_index=True, default=False)),
                ('content', django_quill.fields.QuillField(default='')),
                ('synopsis', models.CharField(max_length=256, null=True)),
            ],
            options={
                'permissions': [('create', 'create a news article'), ('edit', 'edit a given news article')],
            },
        ),
        migrations.CreateModel(
            name='NewsLetterMailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.EmailField(max_length=254)),
            ],
        ),
    ]
