# Generated by Django 4.0.6 on 2024-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettermailinglist',
            old_name='entry',
            new_name='user_email',
        ),
        migrations.AddField(
            model_name='newslettermailinglist',
            name='last_sent',
            field=models.DateField(null=True),
        ),
    ]
