# Generated by Django 4.0.6 on 2024-02-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_newslettermailinglist_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'permissions': [('CanCreateNews', 'Can create a news Article'), ('CanPublishNews', 'Can publish a news Article'), ('CanEditNews', 'Can edit a news Article'), ('CanDeleteNews', 'Can delete a news Article')]},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
