# Generated by Django 4.0.6 on 2024-02-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'default_permissions': (), 'permissions': [('can_manage_news', 'Can manage the news Articles'), ('can_create_news', 'Can create a news Article'), ('can_publish_news', 'Can publish a news Article'), ('can_edit_news', 'Can edit a news Article'), ('can_view_news', 'Can view a news Article'), ('can_delete_news', 'Can delete a news Article')]},
        ),
    ]
