# Generated by Django 4.0.6 on 2024-02-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='synopsis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
