# Generated by Django 5.0 on 2026-02-03 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveCompanyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('scopes', models.TextField(blank=True, default='openid email profile https://www.googleapis.com/auth/drive.file')),
                ('google_sub', models.CharField(blank=True, default='', max_length=255)),
                ('google_email', models.EmailField(blank=True, default='', max_length=254)),
                ('root_folder_id', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('web_view_link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
