# Generated by Django 5.0 on 2026-02-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleDrive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivefile',
            name='uploaded_by',
        ),
    ]
