# Generated by Django 5.0 on 2026-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleDrive', '0002_remove_drivefile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='parent_folder_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
