# Generated by Django 4.0.6 on 2025-09-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GarageSale', '0005_alter_eventdata_supporting_organisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='save_logo_to')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(choices=[('NA', 'No Action'), ('IN', 'Invited'), ('CO', 'Confirmed'), ('RE', 'Rejected'), ('CA', 'Cancelled')], default='NA', max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CraftMarketeers', to='GarageSale.eventdata')),
            ],
            options={
                'permissions': [('can_view', 'Is able to view Craft Market participants'), ('can_suggest', 'Is able to suggest Craft Market participants'), ('can_manage', 'Is able to manage Craft Market participants')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NA', 'No Action'), ('IN', 'Invited'), ('CO', 'Confirmed'), ('RE', 'Rejected'), ('CA', 'Cancelled')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('marketeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftMarket.marketeer')),
            ],
        ),
        migrations.AddIndex(
            model_name='marketeer',
            index=models.Index(fields=['event', 'name'], name='CraftMarket_event_i_d9d526_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['marketeer', 'timestamp'], name='CraftMarket_markete_1aaab2_idx'),
        ),
    ]
