# Generated by Django 4.0.6 on 2025-09-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0007_remove_communicationtemplate_garagesale__categor_e1ca45_idx_and_more'),
        ('CraftMarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marketeer',
            new_name='Marketer',
        ),
        migrations.RemoveIndex(
            model_name='marketer',
            name='CraftMarket_event_i_d9d526_idx',
        ),
        migrations.AddIndex(
            model_name='marketer',
            index=models.Index(fields=['event', 'name'], name='CraftMarket_event_i_05bae5_idx'),
        ),
    ]
