# Generated by Django 4.0.6 on 2025-10-11 09:39

import CraftMarket.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftMarket', '0002_rename_marketeer_marketer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='marketeer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='CraftMarket.marketer'),
        ),
        migrations.AlterField(
            model_name='history',
            name='state',
            field=models.CharField(choices=[('NW', 'New'), ('IN', 'Invited'), ('CO', 'Confirmed'), ('RE', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=CraftMarket.models.save_logo_to),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='state',
            field=models.CharField(choices=[('NW', 'New'), ('IN', 'Invited'), ('CO', 'Confirmed'), ('RE', 'Rejected')], default='NW', max_length=2),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['marketeer', 'state', 'timestamp'], name='CraftMarket_markete_ba01bc_idx'),
        ),
        migrations.AddIndex(
            model_name='marketer',
            index=models.Index(condition=models.Q(('code__isnull', False), ('state', 'IN')), fields=['email', 'code'], name='with_code'),
        ),
    ]
