# Generated by Django 4.0.6 on 2025-10-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftMarket', '0003_marketer_code_alter_history_marketeer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='website',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
