# Generated by Django 4.0.6 on 2025-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftMarket', '0004_marketer_website_alter_marketer_email'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketer',
            name='CraftMarket_event_i_05bae5_idx',
        ),
        migrations.RenameField(
            model_name='marketer',
            old_name='name',
            new_name='trading_name',
        ),
        migrations.AddIndex(
            model_name='marketer',
            index=models.Index(fields=['event', 'trading_name'], name='CraftMarket_event_i_4d1952_idx'),
        ),
    ]
