# Generated by Django 4.0.6 on 2025-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftMarket', '0005_remove_marketer_craftmarket_event_i_05bae5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
