# Generated by Django 4.1 on 2025-12-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftMarket', '0006_marketer_contact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketer',
            options={'default_permissions': (), 'permissions': [('suggest_marketer', 'Is able to suggest Craft Market participants'), ('view_marketer', 'Is able to view details of Craft Market participants'), ('edit_marketer', 'Is able to change details and states Craft Market participants'), ('delete_marketer', 'Is able to remove Craft Market participants')]},
        ),
    ]
