# Generated by Django 4.1 on 2026-01-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftMarket', '0007_alter_marketer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketer',
            options={},
        ),
    ]
