# Generated by Django 4.1 on 2026-01-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftMarket', '0008_alter_marketer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketer',
            options={'permissions': (('suggest_marketeer', 'Can suggest a marketeer'), ('view_marketeer', 'Can view a marketeer'), ('edit_marketeer', 'Can edit a marketeer'), ('delete_marketeer', 'Can delete a marketeer'))},
        ),
    ]
