# Generated by Django 4.1 on 2026-01-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftMarket', '0009_alter_marketer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketer',
            options={'default_permissions': (), 'permissions': (('suggest_marketer', 'Can suggest a marketeer'), ('view_marketer', 'Can view a marketeer'), ('edit_marketer', 'Can edit a marketeer'), ('delete_marketer', 'Can delete a marketeer'))},
        ),
    ]
