"""
Django settings for GarageSale project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Site specific credentials
from credentials import db_credentials as db_credentials
from credentials import django_secret_key
from credentials import email_credentials
from credentials import hosts
from credentials import GoogleMap_credentials
import os

try:
    from credentials import test_server
except ImportError:
    test_server = None

TEST_SERVER = test_server.TEST_SERVER if test_server else False

try:
    from credentials import debug
except ImportError:
    debug = None

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if debug and TEST_SERVER:
    LOGGING = {
        "version": 1,
        'formatters': { 'standard': {
            'format': '%(asctime)s: %(levelname)s: %(name)s %(module)s %(filename)s -> %(funcName)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'    }
        },
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                'formatter': 'standard',
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "WARNING",
        },
        "loggers": {
            "fontTools.ttLib.ttFont" : {"level": "ERROR"},
            "fontTools.subset" : {"level": "ERROR"},
            "fontTools.subset.timer" : {"level": "ERROR"},
            "django.request": {
                "handlers": ["console"],
                "level": os.getenv("DJANGO_LOG_LEVEL", "ERROR"),
                "propagate": False,
            },
            "CraftMarket.views":{
                "handlers": ["console"],
                "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
                "propagate": False,
            },
            "GarageSale.models": {
                "handlers": ["console"],
                "level": os.getenv("DJANGO_LOG_LEVEL", "WARNING"),
                "propagate": False,
            }
        },
    }
    import logging.config
    logging.config.dictConfig(LOGGING)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = django_secret_key.SECRET_KEY
DEBUG = False if not debug else debug.DEBUG

ALLOWED_HOSTS = hosts.ALLOWED_HOSTS
INTERNAL_IPS = hosts.INTERNAL_IPS

STATIC_URL = '/static/'
STATIC_ROOT = 'static'
MEDIA_ROOT = 'media'
MEDIA_URL = '/media/'

# Application definition

INSTALLED_APPS = [
    'team_pages.apps.TeamPagesConfig',
    'GarageSale.apps.GarageSaleConfig',
    'Location.apps.LocationConfig',
    #    'Billboard.apps.BillboardConfig',
    #    'SaleLocation.apps.SaleLocationConfig',
    'DjangoGoogleMap.apps.DjangoWhat3WordsConfig',
    'Sponsors.apps.SponsorsConfig',
    'CraftMarket.apps.CraftmarketConfig',
    'Accounts.apps.AccountsConfig',
    'user_management.apps.user_managementConfig',
    'News.apps.NewsConfig',
    'django.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_quill',
    'django_summernote',
]

AUTH_USER_MODEL = "user_management.UserExtended"

if DEBUG:
    INSTALLED_APPS.extend(
        ['debug_toolbar',
         'mail_panel', ]
    )

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'GarageSale.middleware.event.CurrentEvent',
]

if DEBUG:
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'GarageSale.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'libraries': {
                'location_tags' : "Location.templatetags.location_data_tags",
                'team_page_tags': "team_pages.templatetags.team_page_tags",
                'event_data_tags': "GarageSale.templatetags.garage_sale_data",
                'user_management_tags': "user_management.templatetags.user_extras",
                'newsletter_tags': "News.templatetags.enrol",
                'sponsor_tags': 'Sponsors.templatetags.social_media',
                'craftmarket': 'CraftMarket.templatetags.craftmarket_framework',
            },
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'GarageSale.middleware.context_processors.test_server'
            ],
        },
    },
]

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
    'mail_panel.panels.MailToolbarPanel',
]

WSGI_APPLICATION = 'GarageSale.wsgi.application'

EMAIL_CREDENTIALS = email_credentials.EMAIL_CREDENTIALS
SERVER_EMAIL = email_credentials.SERVER_EMAIL

ADMINS = [('Tony Flury', 'anthony.flury@btinternet.com')]

if DEBUG:
    EMAIL_BACKEND = 'mail_panel.backend.MailToolbarBackend'
else:
    EMAIL_BACKEND = 'GarageSale.middleware.email.EmailExtended'
    EMAIL_DEFAULT = 'website@BranthamGarageSale.org.uk'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

TIME_ZONE = 'UTC'

DATABASES = db_credentials.db_credentials(BASE_DIR)

SESSION_COOKIE_AGE = 365 * 24 * 60 * 60  # Allow upto 365 days between log ins.

APPS_SETTINGS = {
    'user_management': {'EMAIL_SENDER': 'website@branthamgaragesale.org.uk',
                        'SITE_NAME': 'Brantham Garage Sale',
                        },
    'team_pages' : {'Craft Market':'CraftMarket:TeamPages',},
    "CraftMarket" : {'EmailTemplateCategory': 'CraftMarket',
                     'EmailFrom': 'CraftMarket@BranthamGarageSale.org.uk'},
    "Location": {'EmailTemplateCategory': 'Location',
                    'EmailFrom': 'Website@BranthamGarageSale.org.uk'}
}

GOOGLE_MAP_SETTINGS = GoogleMap_credentials.GOOGLE_MAP_SETTINGS