# Generated by Django 4.1 on 2025-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_transaction_transaction_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['bank_name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('transaction_date', 'description', 'amount')},
        ),
    ]
