# Generated by Django 4.1 on 2025-11-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_account_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('transaction_date', 'description', 'debit', 'credit')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
