# Generated by Django 4.1 on 2025-11-23 13:04

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Subquery, OuterRef


def create_financial_years(apps, schema_editor):
    financial_year = apps.get_model('Accounts', 'FinancialYear')
    financial_year.objects.create(year='2024', year_start='2023-10-01', year_end='2024-9-30')
    financial_year.objects.create(year='2025', year_start='2024-10-01', year_end='2025-9-30')

def normalise_financial_year(apps, schema_editor):
    transaction = apps.get_model('Accounts', 'Transaction')
    f_year = apps.get_model('Accounts', 'FinancialYear')
    f_year_qs = f_year.objects.filter(year_start__lte=OuterRef('transaction_date'), year_end__gte=OuterRef('transaction_date'))
    transaction.objects.update(financial_year=Subquery(f_year_qs.values('id')[:1]))


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_transaction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('year_start', models.DateField()),
                ('year_end', models.DateField()),
            ],
        ),
        migrations.RunPython(create_financial_years),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.financialyear'),
            preserve_default=False,
        ),
        migrations.RunPython(normalise_financial_year),
    ]
