# Generated by Django 4.1 on 2025-11-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_financialyear_transaction_name_split_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_set', to='Accounts.transaction'),
        ),
    ]
