# Generated by Django 4.1 on 2025-11-24 09:13

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunPython

def transfer_splits(apps, schema_editor):
    Transaction = apps.get_model('Accounts', 'Transaction')
    Split = apps.get_model('Accounts', 'Split')
    for split in Split.objects.all():
        parent = split.transaction
        transaction = Transaction.objects.create(name=split.description, description=split.description,
                                                 debit=split.amount if parent.debit is not None else None,
                                                 credit=split.amount if parent.credit is not None else None,
                                                 account=parent.account,
                                                 financial_year=parent.financial_year,
                                                 transaction_date=parent.transaction_date)
        transaction.parent = parent
        transaction.save()
        split.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_split_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.transaction'),
        ),
        RunPython(transfer_splits),
        migrations.DeleteModel(
            name='Split',
        ),
    ]
