# Generated by Django 4.1 on 2025-11-24 11:09
from decimal import Decimal

from django.db import migrations, models
from django.db.migrations import RunPython

def update_balance(apps, schema_editor):
    Transaction = apps.get_model('Accounts', 'Transaction')

    for transaction in Transaction.objects.all().order_by('id'):

        if transaction.parent is not None:
            transaction.balance_before = transaction.parent.balance_before
            transaction.save()
        else:
            previous = Transaction.objects.filter(account=transaction.account, id__lt=transaction.id).order_by('-transaction_date','-id').first()
            if previous:
                credit = previous.credit if previous.credit else Decimal('0.00')
                debit = previous.debit if previous.debit else Decimal('0.00')
                to_date = previous.balance_before + (credit - debit)
                transaction.balance_before = to_date
                transaction.save()
            else:
                transaction.balance_before = transaction.account.starting_balance
                transaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_transaction_parent_delete_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    RunPython(update_balance, reverse_code=migrations.RunPython.noop)
    ]
