# Generated by Django 4.1 on 2026-01-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_transaction_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date'], 'permissions': [('can_upload_transaction', 'Can upload upload'), ('can_report_transaction', 'Can upload report')]},
        ),
    ]
