# Generated by Django 6.0.1 on 2026-01-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_account_last_transaction_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_date'], 'permissions': [('upload_transaction', 'Can upload upload'), ('report_transaction', 'Can upload report')]},
        ),
    ]
