# Generated by Django 6.0.1 on 2026-01-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_remove_transaction_financial_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='balance_before',
            new_name='balance',
        ),
    ]
