# Generated by Django 6.0.1 on 2026-01-15 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_rename_balance_before_transaction_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadhistory',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddIndex(
            model_name='uploaderror',
            index=models.Index(fields=['transaction'], name='ByTransaction'),
        ),
        migrations.AddIndex(
            model_name='uploaderror',
            index=models.Index(fields=['upload_history'], name='ByUploadHistory'),
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['account'], name='ByAccount'),
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['start_date', 'end_date'], name='ByDate'),
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['uploaded_at'], name='ByUploadDate'),
        ),
    ]
