# Generated by Django 6.0.1 on 2026-01-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_alter_uploadhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['category_name']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_transaction_number',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='uploadhistory',
            unique_together={('account', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['category_name'], name='Accounts_ca_categor_8ed407_idx'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['debit_only', 'credit_only'], name='Accounts_ca_debit_o_770d92_idx'),
        ),
    ]
