# Generated by Django 6.0.1 on 2026-01-16 10:38

from django.db import migrations, models

def set_credit_flag(apps, schema_editor):
    Categories = apps.get_model("Accounts", "Categories")
    for category in Categories.objects.all():
        category.credit_debits = 'D' if category.debit_only else 'C'
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='credit_debit',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='C', max_length=1),
        ),
        migrations.RunPython(set_credit_flag),

        migrations.RemoveField(
            model_name='categories',
            name='debit_only',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='credit_only',
        )

    ]
