# Generated by Django 6.0.1 on 2026-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_categories_credit_debits'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categories',
            name='Accounts_ca_debit_o_770d92_idx',
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['credit_debit'], name='Accounts_ca_credit__8b724f_idx'),
        ),
    ]
