# Generated by Django 6.0.1 on 2026-01-18 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_remove_categories_accounts_ca_debit_o_770d92_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.categories'),
        ),
        migrations.AlterField(
            model_name='uploaderror',
            name='upload_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='Accounts.uploadhistory'),
        ),
    ]
