# Generated by Django 5.0 on 2026-02-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_categories_parent_alter_uploaderror_upload_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Accounts.categories',),
        ),
    ]
