# Generated by Django 5.0 on 2026-02-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_publishedreports'),
        ('GoogleDrive', '0002_remove_drivefile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedreports',
            name='report_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoogleDrive.drivefile'),
        ),
    ]
