# Generated by Django 5.0 on 2026-02-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_alter_publishedreports_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Accounts.categories'),
        ),
        migrations.AlterField(
            model_name='publishedreports',
            name='report_type',
            field=models.CharField(max_length=20),
        ),
    ]
