# Generated by Django 5.0 on 2026-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0023_alter_categories_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
