# Generated by Django 4.1 on 2025-03-15 16:49

import Sponsors.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GarageSale', '0002_motd_supporting_eventdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, upload_to=Sponsors.models.save_logo_to)),
                ('description', models.TextField(max_length=1000)),
                ('gift', models.TextField(blank=True, max_length=1000, null=True)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='GarageSale.eventdata')),
                ('lead_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_sponsor', 'Can record a new Sponsor'), ('can_edit_sponsor', 'Can edit an existing Sponsor'), ('can_view_sponsor', 'Can view an existing Sponsor'), ('can_delete_sponsor', 'Can delete an existing Sponsor'), ('can_confirm_sponsor', 'Can confirm a Sponsor')],
                'default_permissions': (),
            },
        ),
    ]
