# Generated by Django 4.0.6 on 2024-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
