# Generated by Django 4.1 on 2026-01-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'permissions': [('confirm_sponsor', 'Can confirm a Sponsor')]},
        ),
    ]
