# Generated by Django 4.0.6 on 2024-02-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0005_alter_sponsor_description_alter_sponsor_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
