# Generated by Django 4.0.6 on 2024-02-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0006_sponsor_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'default_permissions': (), 'permissions': [('can_create_sponsor', 'Can record a new Sponsor'), ('can_edit_sponsor', 'Can edit an existing Sponsor'), ('can_view_sponsor', 'Can view an existing Sponsor'), ('can_delete_sponsor', 'Can delete an existing Sponsor'), ('can_confirm_sponsor', 'Can confirm a Sponsor')]},
        ),
    ]
