# Generated by Django 4.0.6 on 2024-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0008_alter_sponsor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
