# Generated by Django 4.0.6 on 2024-02-29 10:18

import Sponsors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0009_alter_sponsor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, upload_to=Sponsors.models.save_logo_to),
        ),
    ]
