# Generated by Django 4.1 on 2025-03-14 10:08

import GarageSale.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import django_quill.fields


class Migration(migrations.Migration):

    replaces = [('GarageSale', '0001_initial'), ('GarageSale', '0002_initial'), ('GarageSale', '0003_delete_location'), ('GarageSale', '0004_alter_eventdata_close_billboard_bookings_and_more'), ('GarageSale', '0005_supporting_eventdata_supporting_organisations'), ('GarageSale', '0006_alter_supporting_logo'), ('GarageSale', '0007_remove_supporting_by_event'), ('GarageSale', '0008_alter_eventdata_supporting_organisations'), ('GarageSale', '0009_alter_supporting_managers_supporting_index')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_trustee', 'Is a member of the Charity Trustee Team'), ('is_administrator', 'Is a administrator for the website'), ('is_manager', 'Is a manager of the website')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MOTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_from', models.DateField()),
                ('content', django_quill.fields.QuillField(default='')),
                ('synopsis', models.CharField(max_length=256, null=True)),
            ],
            options={
                'permissions': [('can_create_motd', 'Can create a new MotD'), ('can_edit_motd', 'Can edit an existing MotD'), ('can_view_motd', 'Can view an existing MotD'), ('can_delete_motd', 'Can delete an existing MotD')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Supporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to=GarageSale.models.save_supported_logo_to)),
                ('website', models.URLField()),
                ('index', models.IntegerField(default=0)),
            ],
            managers=[
                ('by_index', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_logo', models.ImageField(null=True, upload_to=GarageSale.models.save_event_logo_to)),
                ('event_date', models.DateField()),
                ('open_billboard_bookings', models.DateField(null=True)),
                ('close_billboard_bookings', models.DateField(null=True)),
                ('open_sales_bookings', models.DateField(null=True)),
                ('close_sales_bookings', models.DateField(null=True)),
                ('use_from', models.DateField()),
                ('supporting_organisations', models.ManyToManyField(related_name='by_event', to='GarageSale.supporting')),
            ],
            options={
                'permissions': [('can_create_event', 'Can create a new Event'), ('can_edit_event', 'Can edit an existing Event'), ('can_view_event', 'Can view an existing Event'), ('can_delete_event', 'Can delete an existing Event'), ('can_use_event', 'Can use an existing Event')],
                'default_permissions': (),
            },
        ),
    ]
