# Generated by Django 4.1 on 2025-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_trustee', 'Is a member of the Charity Trustee Team'), ('is_administrator', 'Is a administrator for the website'), ('is_manager', 'Is a manager of the website')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
