# Generated by Django 4.0.6 on 2024-10-05 15:48

import GarageSale.models
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_trustee', 'Is a member of the Charity Trustee Team'), ('is_administrator', 'Is a administrator for the website'), ('is_manager', 'Is a manager of the website')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_logo', models.ImageField(blank=True, upload_to=GarageSale.models.save_event_logo_to)),
                ('event_date', models.DateField()),
                ('open_billboard_bookings', models.DateField()),
                ('close_billboard_bookings', models.DateField()),
                ('open_sales_bookings', models.DateField()),
                ('close_sales_bookings', models.DateField()),
                ('use_from', models.DateField()),
            ],
            options={
                'permissions': [('can_create_event', 'Can create a new Event'), ('can_edit_event', 'Can edit an existing Event'), ('can_view_event', 'Can view an existing Event'), ('can_delete_event', 'Can delete an existing Event'), ('can_use_event', 'Can use an existing Event')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=80)),
                ('street_name', models.CharField(max_length=200)),
                ('town', models.CharField(default='Brantham', max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='MOTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_from', models.DateField()),
                ('content', django_quill.fields.QuillField(default='')),
                ('synopsis', models.CharField(max_length=256, null=True)),
            ],
            options={
                'permissions': [('can_create_motd', 'Can create a new MotD'), ('can_edit_motd', 'Can edit an existing MotD'), ('can_view_motd', 'Can view an existing MotD'), ('can_delete_motd', 'Can delete an existing MotD')],
                'default_permissions': (),
            },
        ),
    ]
