# Generated by Django 4.0.6 on 2024-02-04 08:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_logo', models.ImageField(upload_to='')),
                ('event_date', models.DateField()),
                ('open_billboard_bookings', models.DateField()),
                ('close_billboard_bookings', models.DateField()),
                ('open_sales_bookings', models.DateField()),
                ('close_sales_bookings', models.DateField()),
                ('use_from', models.DateField()),
            ],
            managers=[
                ('current_event', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
