# Generated by Django 4.0.6 on 2024-10-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
