# Generated by Django 4.0.6 on 2025-06-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0002_motd_supporting_eventdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='myGoogleMaps',
            field=models.URLField(blank=True, null=True),
        ),
    ]
