# Generated by Django 4.0.6 on 2024-02-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0002_eventdata_delete_settings'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventdata',
            managers=[
            ],
        ),
    ]
