# Generated by Django 4.1 on 2024-11-08 10:25

import GarageSale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0003_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='close_billboard_bookings',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='close_sales_bookings',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_logo',
            field=models.ImageField(null=True, upload_to=GarageSale.models.save_event_logo_to),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='open_billboard_bookings',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='open_sales_bookings',
            field=models.DateField(null=True),
        ),
    ]
