# Generated by Django 4.0.6 on 2025-06-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0003_eventdata_mygooglemaps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='myGoogleMaps',
            new_name='myGoogleMapURL',
        ),
    ]
