# Generated by Django 4.1 on 2025-01-31 15:55

import GarageSale.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0004_alter_eventdata_close_billboard_bookings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=GarageSale.models.save_supported_logo_to)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='eventdata',
            name='supporting_organisations',
            field=models.ManyToManyField(to='GarageSale.supporting'),
        ),
    ]
