# Generated by Django 4.0.6 on 2025-09-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0004_rename_mygooglemaps_eventdata_mygooglemapurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='supporting_organisations',
            field=models.ManyToManyField(blank=True, related_name='by_event', to='GarageSale.supporting'),
        ),
    ]
