# Generated by Django 4.0.6 on 2024-02-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0004_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='event_logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
