# Generated by Django 4.0.6 on 2024-02-18 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0005_alter_eventdata_event_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='close_billboard_bookings',
            field=models.DateField(default=datetime.date(2024, 2, 18)),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='close_sales_bookings',
            field=models.DateField(default=datetime.date(2024, 2, 18)),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateField(default=datetime.date(2024, 2, 18)),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='open_billboard_bookings',
            field=models.DateField(default=datetime.date(2024, 2, 18)),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='open_sales_bookings',
            field=models.DateField(default=datetime.date(2024, 2, 18)),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='use_from',
            field=models.DateField(default=datetime.date(2024, 2, 18)),
        ),
    ]
