# Generated by Django 4.0.6 on 2025-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0005_alter_eventdata_supporting_organisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('transition', models.CharField(blank=True, max_length=5, null=True)),
                ('subject', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('signature', models.TextField(blank=True, max_length=500, null=True)),
                ('use_from', models.DateField()),
            ],
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['category', '-use_from'], name='GarageSale__categor_e1ca45_idx'),
        ),
    ]
