# Generated by Django 4.1 on 2025-02-07 14:46

import GarageSale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0005_supporting_eventdata_supporting_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporting',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=GarageSale.models.save_supported_logo_to),
        ),
    ]
