# Generated by Django 4.0.6 on 2025-09-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0006_communicationtemplate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communicationtemplate',
            name='GarageSale__categor_e1ca45_idx',
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='summary',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['category', '-use_from'], name='CategoryByDate'),
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['category', 'transition', '-use_from'], name='CategoryTransitionByDate'),
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['category', 'summary', '-use_from'], name='CategorySummaryByDate'),
        ),
    ]
