# Generated by Django 4.1 on 2025-02-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0006_alter_supporting_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporting',
            name='by_event',
        ),
    ]
