# Generated by Django 4.0.6 on 2024-02-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0006_alter_eventdata_close_billboard_bookings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='close_billboard_bookings',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='close_sales_bookings',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='open_billboard_bookings',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='open_sales_bookings',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='use_from',
            field=models.DateField(),
        ),
    ]
