# Generated by Django 4.0.6 on 2025-10-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0007_remove_communicationtemplate_garagesale__categor_e1ca45_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communicationtemplate',
            old_name='content',
            new_name='html_content',
        ),
    ]
