# Generated by Django 4.1 on 2025-02-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0007_remove_supporting_by_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='supporting_organisations',
            field=models.ManyToManyField(related_name='by_event', to='GarageSale.supporting'),
        ),
    ]
