# Generated by Django 4.0.6 on 2025-10-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0008_rename_content_communicationtemplate_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtemplate',
            name='transition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
