# Generated by Django 4.0.6 on 2024-02-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0008_alter_eventdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={'permissions': [('CanEventCreate', 'Can create a new Event'), ('CanEventEdit', 'Can edit an existing Event'), ('CanEventDelete', 'Can delete an existing Event')]},
        ),
    ]
