# Generated by Django 4.1 on 2025-02-07 16:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0008_alter_eventdata_supporting_organisations'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='supporting',
            managers=[
                ('by_index', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='supporting',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
