# Generated by Django 4.0.6 on 2024-02-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0009_alter_eventdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motd',
            options={'permissions': [('CanMotdCreate', 'Can create a new MotD'), ('CanMotdEdit', 'Can edit an existing MotD'), ('CanMotdDelete', 'Can delete an existing MotD')]},
        ),
    ]
