# Generated by Django 4.1 on 2025-03-14 10:32

import GarageSale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0001_squashed_0009_alter_supporting_managers_supporting_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='General',
        ),
        migrations.AlterModelManagers(
            name='supporting',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_logo',
            field=models.FileField(null=True, upload_to=GarageSale.models.save_event_logo_to),
        ),
        migrations.AlterField(
            model_name='supporting',
            name='index',
            field=models.IntegerField(),
        ),
    ]
