# Generated by Django 4.1 on 2025-10-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0009_alter_communicationtemplate_transition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='templates/')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='GarageSale.communicationtemplate')),
            ],
        ),
    ]
