# Generated by Django 4.1 on 2025-10-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0010_templateattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateattachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
