# Generated by Django 4.0.6 on 2024-02-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0010_alter_motd_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={'default_permissions': (), 'permissions': [('CanEventCreate', 'Can create a new Event'), ('CanEventEdit', 'Can edit an existing Event'), ('CanEventDelete', 'Can delete an existing Event')]},
        ),
        migrations.AlterModelOptions(
            name='motd',
            options={'default_permissions': (), 'permissions': [('CanMotdCreate', 'Can create a new MotD'), ('CanMotdEdit', 'Can edit an existing MotD'), ('CanMotdDelete', 'Can delete an existing MotD')]},
        ),
    ]
