# Generated by Django 4.1 on 2025-11-01 16:12

import GarageSale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0011_alter_templateattachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtemplate',
            name='signature',
            field=models.TextField(blank=True, help_text='Signature line for email', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='subject',
            field=models.CharField(help_text='Subject line for email', max_length=180),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='summary',
            field=models.CharField(blank=True, help_text='Summary line for display', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='templateattachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=GarageSale.models.save_template_attachment_to),
        ),
    ]
