# Generated by Django 4.0.6 on 2024-02-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0011_alter_eventdata_options_alter_motd_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={'default_permissions': (), 'permissions': [('can_event_create', 'Can create a new Event'), ('can_event_edit', 'Can edit an existing Event'), ('can_event_delete', 'Can delete an existing Event')]},
        ),
    ]
