# Generated by Django 4.0.6 on 2024-02-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0012_alter_eventdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motd',
            options={'default_permissions': (), 'permissions': [('can_create_motd', 'Can create a new MotD'), ('can_edit_motd', 'Can edit an existing MotD'), ('can_view_motd', 'Can edit an existing MotD'), ('can_delete_motd', 'Can delete an existing MotD')]},
        ),
    ]
