# Generated by Django 4.1 on 2025-11-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0012_alter_communicationtemplate_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateattachment',
            old_name='attachment',
            new_name='attached_file',
        ),
    ]
