# Generated by Django 4.1 on 2025-11-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0013_rename_attachment_templateattachment_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtemplate',
            name='signature',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='subject',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='communicationtemplate',
            name='summary',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
