# Generated by Django 4.1 on 2025-11-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0014_alter_communicationtemplate_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateattachment',
            old_name='name',
            new_name='template_name',
        ),
    ]
