# Generated by Django 4.0.6 on 2024-02-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0014_alter_motd_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={'default_permissions': (), 'permissions': [('can_create_event', 'Can create a new Event'), ('can_edit_event', 'Can edit an existing Event'), ('can_view_event', 'Can edit an existing Event'), ('can_delete_event', 'Can delete an existing Event')]},
        ),
    ]
