# Generated by Django 4.0.6 on 2024-02-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0015_alter_eventdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={'default_permissions': (), 'permissions': [('can_create_event', 'Can create a new Event'), ('can_edit_event', 'Can edit an existing Event'), ('can_view_event', 'Can view an existing Event'), ('can_delete_event', 'Can delete an existing Event'), ('can_use_event', 'Can use an existing Event')]},
        ),
    ]
