# Generated by Django 4.1 on 2026-01-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0015_rename_name_templateattachment_template_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': ('is_team_member',), 'managed': False, 'permissions': (('is_team_member', 'Can access admin pages'),)},
        ),
        migrations.AlterModelOptions(
            name='motd',
            options={},
        ),
        migrations.AlterField(
            model_name='templateattachment',
            name='template_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
