# Generated by Django 4.1 on 2026-01-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0016_alter_eventdata_options_alter_general_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='General',
        ),
        migrations.AlterModelOptions(
            name='supporting',
            options={'permissions': [('can_create_supporting', 'Can create a record for a supporting organisation')]},
        ),
    ]
