# Generated by Django 4.0.6 on 2024-02-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0017_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
