# Generated by Django 5.0 on 2026-03-14 09:03

from django.db import migrations, models

def _move_from_quill(apps, schema_editor):
    motds = apps.get_model("GarageSale", "MOTD")
    for entry in motds.objects.all():
        # Try to decode the JSON content from Quill - if it fails simply use the plain text
        try:
            entry.html_content = entry.content.html
        except django_quill.quill.QuillParseError:
            entry.html_content = entry.content
        entry.save()

def _move_to_quill(apps, schema_editor):
    motds = apps.get_model("GarageSale", "MOTD")
    for entry in motds.objects.all():
        entry.content.html = entry.html_content
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0017_delete_general_alter_supporting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='motd',
            name='html_content',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(_move_from_quill, reverse_code=_move_to_quill ),
        migrations.RemoveField( model_name='MOTD', name='content'),
        migrations.RenameField(model_name='MOTD', old_name='html_content', new_name='content'),
    ]
