# Generated by Django 4.0.6 on 2024-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0018_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_trustee', 'Is a member of the Charity Trustee Team'), ('is_administrator', 'Is a administrator for the website'), ('is_manager', 'Is a manager of the website')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
