# Generated by Django 4.0.6 on 2024-02-29 10:18

import GarageSale.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0019_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='event_logo',
            field=models.ImageField(blank=True, upload_to=GarageSale.models.save_event_logo_to),
        ),
    ]
