# Generated by Django 4.0.6 on 2024-10-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
