# Generated by Django 4.0.6 on 2024-10-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GarageSale', '0001_initial'),
        ('Billboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardlocations',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billboards', to='GarageSale.eventdata'),
        ),
        migrations.AddField(
            model_name='billboardlocations',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billboards', to='GarageSale.location'),
        ),
    ]
