# Generated by Django 4.0.6 on 2024-02-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Billboard', '0002_billboardlocations_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboardlocations',
            name='email',
        ),
        migrations.RemoveField(
            model_name='billboardlocations',
            name='name',
        ),
        migrations.AddField(
            model_name='billboardlocations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billboards', to=settings.AUTH_USER_MODEL),
        ),
    ]
