# Generated by Django 4.0.6 on 2024-02-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0004_location'),
        ('Billboard', '0003_remove_billboardlocations_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboardlocations',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='billboardlocations',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='billboardlocations',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='billboardlocations',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='billboardlocations',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='billboardlocations',
            name='town',
        ),
        migrations.RemoveField(
            model_name='billboardlocations',
            name='user',
        ),
        migrations.AddField(
            model_name='billboardlocations',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billboards', to='GarageSale.location'),
        ),
    ]
