# Generated by Django 4.0.6 on 2024-03-06 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard', '0004_remove_billboardlocations_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardlocations',
            name='creation_date',
            field=models.DateField(auto_created=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
