# Generated by Django 4.0.6 on 2024-10-05 15:48

import SaleLocation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GarageSale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_aid', models.BooleanField(default=False, verbose_name='Sign up for GiftAid ?')),
                ('minimum_paid', models.BooleanField(default=False)),
                ('category', SaleLocation.models.MultipleChoiceField(default=['Other'], max_length=500, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sales', to='GarageSale.eventdata')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sales', to='GarageSale.location')),
            ],
        ),
    ]
