# Generated by Django 4.0.6 on 2024-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=80)),
                ('street_name', models.CharField(max_length=200)),
                ('town', models.CharField(default='Brantham', max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=80)),
                ('minimum_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
