# Generated by Django 4.0.6 on 2024-02-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0003_alter_eventdata_managers'),
        ('SaleLocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelocations',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sales', to='GarageSale.eventdata'),
        ),
    ]
