# Generated by Django 4.0.6 on 2024-02-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarageSale', '0004_location'),
        ('SaleLocation', '0002_salelocations_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salelocations',
            name='email',
        ),
        migrations.RemoveField(
            model_name='salelocations',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='salelocations',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='salelocations',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salelocations',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='salelocations',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='salelocations',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='salelocations',
            name='town',
        ),
        migrations.AddField(
            model_name='salelocations',
            name='gift_aid',
            field=models.BooleanField(default=False, verbose_name='Sign up for GiftAid ?'),
        ),
        migrations.AddField(
            model_name='salelocations',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sales', to='GarageSale.location'),
        ),
    ]
