# Generated by Django 4.0.6 on 2024-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleLocation', '0003_remove_salelocations_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelocations',
            name='category',
            field=models.CharField(default='various', max_length=20),
        ),
    ]
