# Generated by Django 4.0.6 on 2024-02-12 17:48

import SaleLocation.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleLocation', '0004_salelocations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelocations',
            name='category',
            field=SaleLocation.models.MultipleChoiceField(default=['Other'], max_length=20, null=True),
        ),
    ]
