# Generated by Django 4.0.6 on 2024-03-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleLocation', '0007_salelocations_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelocations',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
