# Generated by Django 4.0.6 on 2024-02-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('sourceIP', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='GET', max_length=4)),
                ('username', models.CharField(max_length=256)),
                ('user_agent', models.CharField(max_length=256)),
                ('response_code', models.IntegerField()),
            ],
        ),
    ]
