# Generated by Django 4.0.6 on 2024-02-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageVisits', '0002_pagevisit_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
