# Generated by Django 4.0.6 on 2024-03-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageVisits', '0003_alter_pagevisit_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='referer',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.CharField(max_length=500),
        ),
    ]
